### ISSUE TITLE
Package Task Cleanup

### ISSUE THREAD

**Issue by ASVincent** [OpenDataCubePipelines/tesp#45]
Currently the package tasks creates 2 layers for the work directory in order to handle multiple granules delivered in one package (multi-granule).
Setting cleanup=true in the configuration file will only delete the directory for the granule and not the package, thus not fully cleaning up after the job has been completed. (The Package task currently cannot delete the package directory because the tasks in a multi-granule processing aren't aware of the completion of each other).

Issue is fairly minor, results in additional inode usage until the process can be cleaned up.

**Comment by sixy6e** [comment]
Ok to ignore for now.
